name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: taskly
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: User@12345
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Create _work directory
        run: mkdir -p /home/runner/actions_runner/_work

      - name: Clone Repository into _work
        uses: actions/checkout@v4
        with:
          path: /home/runner/actions_runner/_work/taskly-backend

      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4'

      - name: Copy .env
        working-directory: /home/runner/actions_runner/_work/taskly-backend
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        working-directory: /home/runner/actions_runner/_work/taskly
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate Key
        working-directory: /home/runner/actions_runner/_work/taskly-backend
        run: php artisan key:generate

      - name: Set Directory Permissions
        working-directory: /home/runner/actions_runner/_work/taskly-backend
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        working-directory: /home/runner/actions_runner/_work/taskly-backend
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: taskly
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: laravel_user
          DB_PASSWORD: User@12345
        run: php artisan migrate --force

      - name: Execute Tests
        working-directory: /home/runner/actions_runner/_work/taskly-backend
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: taskly
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: laravel_user
          DB_PASSWORD: User@12345
        run: php artisan test
